### ISSUE TITLE
关闭标签 的提示增加 “撤消”功能

### ISSUE THREAD

**Issue by FTsong** [anpho/PaperBird#10]
如题

**Comment by MerrickZ** [comment]
无截图不处理，你咬我啊哈哈哈哈

**Comment by MerrickZ** [comment]
现在关闭标签前会有提示是否要关闭
点完确认以后标签才会关闭
关闭后再出来个toast说 这个页面已经被关闭了，右边出来个 撤销 按钮
这个toast会持续10秒钟，时间改不了
碰到 撤销 就会立即打开原来的标签页
我觉得有点太麻烦了。
